aranya-project/aranya-core

- crates/aranya-crypto/src/afc/mod.rs
- crates/aranya-crypto/src/apq.rs
- crates/aranya-crypto/src/lib.rs
- crates/aranya-fast-channels/src/mutex.rs
- crates/aranya-idam-ffi/src/lib.rs
- crates/aranya-model/src/tests/mod.rs
- crates/aranya-policy-vm/tests/vm.rs
- crates/aranya-runtime/src/client/session.rs
- crates/aranya-runtime/src/testing/vm.rs
Original PR:
https://git.spideroak-inc.com/spideroak-inc/aranya-core/pull/83
> docs: update references from flow3-docs to aranya-docs

- supply-chain/config.toml
- supply-chain/imports.lock
> cargo vet: disable audit-as-crates-io for workspace crates

- .github/workflows/release-plz.yml
The `release-plz` PR is unable to update crate versions correctly when there are complex dependency trees with newer versions. We'll need to update crate versions in a PR manually for now until we can add the needed functionality to the tooling.
> rm release-plz pr

- crates/aranya-runtime/src/client/session.rs
This is more consistent since we don't currently limit the command size anywhere else. We may want to handle session commands differently anyways. Limiting will later be handled by #84.
> Remove limit on session command

- README.md
Adds a high-level description of what is included in this repository. 
Also, adds a `Maintainers` section and rearranges the contributing section to be next to this addition (matching the format of the aranya repo: https://github.com/aranya-project/aranya/pull/39).
> Describe repo contents in README

- Cargo.lock
- Cargo.toml
- crates/aranya-quic-syncer/Cargo.toml
- crates/aranya-quic-syncer/benches/quic_syncer.rs
- crates/aranya-quic-syncer/examples/quic_syncer.rs
- crates/aranya-quic-syncer/tests/test.rs
- deny.toml
- supply-chain/audits.toml
- supply-chain/config.toml
- supply-chain/imports.lock
- Update `rcgen` and use aws crypto for it and `s2n-quic` instead of `ring`
- `ring`'s https://rustsec.org/advisories/RUSTSEC-2025-0009 required updating `rcgen`, which now has a flag for choosing aws crypto, so I switched off `ring` entirely.
- Update `scc` and `sdd` off yanked versions.
- Allow https://rustsec.org/advisories/RUSTSEC-2024-0436.html
- it doesn't seem problematic and has no easy migration at the moment.
> Security updates

- crates/aranya-policy-compiler/src/compile.rs
- crates/aranya-policy-compiler/src/compile/target.rs
- crates/aranya-policy-compiler/src/tests.rs
- crates/aranya-policy-ifgen-macro/src/value.rs
- crates/aranya-policy-module/src/data.rs
- crates/aranya-policy-module/src/module.rs
- crates/aranya-policy-vm/src/machine.rs
- crates/aranya-policy-vm/tests/vm.rs
Enum values are now stored as `Vec<usize>`s in the VM.
> Close #73: Change enum representation to be orderable

- crates/aranya-policy-ast/src/lib.rs
- crates/aranya-policy-ast/src/util.rs
- crates/aranya-policy-compiler/src/compile.rs
- crates/aranya-policy-compiler/src/compile/types.rs
- crates/aranya-policy-compiler/src/tests.rs
- crates/aranya-policy-lang/src/lang/parse.rs
- crates/aranya-policy-lang/src/lang/parse/tests.rs
- crates/aranya-policy-vm-explorer/src/main.rs
- crates/aranya-policy-vm/tests/vm.rs
> More type checking

- Cargo.lock
- crates/aranya-afc-util/CHANGELOG.md
- crates/aranya-afc-util/Cargo.toml
- crates/aranya-crypto-ffi/CHANGELOG.md
- crates/aranya-crypto-ffi/Cargo.toml
- crates/aranya-crypto/CHANGELOG.md
- crates/aranya-crypto/Cargo.toml
- crates/aranya-device-ffi/CHANGELOG.md
- crates/aranya-device-ffi/Cargo.toml
- crates/aranya-envelope-ffi/CHANGELOG.md
- crates/aranya-envelope-ffi/Cargo.toml
- crates/aranya-fast-channels/CHANGELOG.md
- crates/aranya-fast-channels/Cargo.toml
- crates/aranya-idam-ffi/CHANGELOG.md
- crates/aranya-idam-ffi/Cargo.toml
- crates/aranya-model/Cargo.toml
- crates/aranya-perspective-ffi/CHANGELOG.md
- crates/aranya-perspective-ffi/Cargo.toml
- crates/aranya-policy-compiler/CHANGELOG.md
- crates/aranya-policy-compiler/Cargo.toml
- crates/aranya-policy-ifgen/CHANGELOG.md
- crates/aranya-policy-ifgen/Cargo.toml
- crates/aranya-policy-module/CHANGELOG.md
- crates/aranya-policy-module/Cargo.toml
- crates/aranya-policy-vm-explorer/Cargo.toml
- crates/aranya-policy-vm/CHANGELOG.md
- crates/aranya-policy-vm/Cargo.toml
- crates/aranya-quic-syncer/Cargo.toml
- crates/aranya-runtime/CHANGELOG.md
- crates/aranya-runtime/Cargo.toml
This unblocks user -> device rename for the aranya repo.
```
aranya-afc-util@0.5.0
aranya-crypto-ffi@0.5.0
aranya-crypto@0.4.0
aranya-device-ffi@0.5.0
aranya-envelope-ffi@0.5.0
aranya-fast-channels@0.5.0
aranya-idam-ffi@0.5.0
aranya-perspective-ffi@0.5.0
aranya-policy-compiler@0.5.0
aranya-policy-ifgen@0.5.0
aranya-policy-module@0.5.0
aranya-policy-vm@0.5.0
aranya-runtime@0.5.0
```
> aranya-core: user -> device crate release

- crates/aranya-policy-ast/src/ast.rs
- crates/aranya-policy-compiler/src/compile.rs
- crates/aranya-policy-compiler/src/tests.rs
- crates/aranya-policy-lang/src/lang/parse.rs
- crates/aranya-policy-lang/src/lang/parse/policy.pest
- crates/aranya-policy-lang/src/lang/parse/tests.rs
- crates/aranya-policy-vm/src/machine.rs
- crates/aranya-policy-vm/tests/vm.rs
Allows `match` to be use as an expression. E.g.:
```
let x = match n {
1 => {
:"one"
}
_ => "other"
}
```
> Close #110: Add match expressions.

- crates/aranya-policy-compiler/src/compile.rs
- crates/aranya-policy-compiler/src/tests.rs
Close #103: Variables defined in `if` and `match` blocks are now scoped to the blocks.
> Close #103: `if`, `match` statements now limit scope to their blocks.

- crates/aranya-capi-codegen-test/Cargo.toml
- crates/aranya-capi-codegen-test/src/defs.rs
- crates/aranya-capi-codegen-test/src/generated.rs
- crates/aranya-capi-codegen/src/ast/expand.rs
Since we're making AFC experimental, some types are now conditionally defined, which causes errors in our FFI wrapper since the type path doesn't exist. This should fix that by copying the same `#[cfg()]` flags over.
> aranya-capi-codegen: Apply `#[cfg()]` Attributes To FFI Wrapper

- crates/aranya-policy-compiler/src/tests.rs
- crates/aranya-policy-lang/src/lang/parse.rs
- crates/aranya-policy-lang/src/lang/parse/policy.pest
- crates/aranya-policy-lang/src/lang/parse/tests.rs
- crates/aranya-policy-lang/src/lang/tictactoe-policy.md
- crates/aranya-policy-vm/tests/bits/policies.rs
Closes #163. `if` expression arms are now block expressions, e.g.
```
let x = if y > 0 {
let x = y + 1
: x
} else { :0 }
```
> aranya-policy-lang: allow block expressions in `if` expressions.

- crates/aranya-capi-codegen-test/src/defs.rs
- crates/aranya-capi-codegen-test/src/generated.rs
- crates/aranya-capi-codegen/src/ast/expand.rs
Closes #160
- Convert to a "FFI enum" using it's `From` impl when a trampoline function returns the underlying enum type
- When there's an output param, try to convert to a "FFI enum" from it's underlying type by calling `Into::into`
- Add `ByMutPtr` impl for "FFI enums"
> (capi-codegen) Enum return types

- Cargo.lock
- crates/aranya-capi-codegen-test/Cargo.toml
- crates/aranya-capi-codegen/CHANGELOG.md
- crates/aranya-capi-codegen/Cargo.toml
- crates/aranya-capi-core/CHANGELOG.md
- crates/aranya-capi-core/Cargo.toml
- crates/aranya-capi-macro/CHANGELOG.md
- crates/aranya-capi-macro/Cargo.toml
Release `aranya-capi-codegen` to use return enums feature from:
https://github.com/aranya-project/aranya-core/pull/195
This PR can be referenced for the last time this crate was released:
https://github.com/aranya-project/aranya-core/pull/189
> release: bump aranya-capi-codegen to 0.2.3

- crates/aranya-capi-codegen-test/src/defs.rs
- crates/aranya-capi-codegen-test/src/generated.rs
- crates/aranya-capi-core/src/types/allowed.rs
As well as ByInput and ByConstPtr.
To support https://github.com/aranya-project/aranya/pull/183/files#r2036026419
> (capi-codegen) Implement ByMutPtr trait for Arrays

- crates/aranya-aqc-util/Cargo.toml
- crates/aranya-capi-codegen-test/Cargo.toml
- crates/aranya-model/Cargo.toml
- crates/aranya-policy-vm-explorer/Cargo.toml
- crates/aranya-quic-syncer/Cargo.toml
- supply-chain/config.toml
Fixes `cargo vet` check: https://github.com/aranya-project/aranya-core/actions/runs/14389133920/job/40351787630
Removes `version` from `path` dependencies in crates that have not been published and from `dev-dependencies`.
> chore: fix vet config and remove unused path dep versions

- crates/aranya-capi-core/src/safe.rs
I think it was meant to be `Alias<Safe<U>> for Safe<T>`, but that also seems not very useful since the type ID will presumably mismatch? I am just removing it for now since it is not needed.
> capi-core: remove `Safe` `Alias` impl

- crates/aranya-policy-ast/src/util.rs
- crates/aranya-policy-module/src/data.rs
- crates/aranya-policy-vm/tests/vm.rs
- crates/aranya-runtime/src/vm_policy/io.rs
```
enum Status { A, B }
fact Foo[s: enum Status] => { s string }
action a() {
let f = unwrap query Foo[s: Status::A] => {}
}
```
> Close #194: Allow enums in key values.

- crates/aranya-crypto/examples/hsm/hsm.rs
- crates/aranya-crypto/examples/hsm/main.rs
- crates/aranya-crypto/src/ciphersuite.rs
- crates/aranya-crypto/src/default.rs
- crates/aranya-crypto/src/id.rs
- crates/aranya-crypto/src/keystore/fs_keystore/store.rs
- crates/aranya-crypto/src/test_util/engine.rs
- crates/aranya-crypto/src/test_util/mod.rs
- crates/aranya-quic-syncer/tests/test.rs
- crates/aranya-runtime/src/client/transaction.rs
- crates/aranya-runtime/src/command.rs
- crates/aranya-runtime/src/protocol.rs
- crates/aranya-runtime/src/storage/linear/libc/path.rs
- crates/aranya-runtime/src/sync/requester.rs
- crates/aranya-runtime/src/sync/responder.rs
- crates/aranya-runtime/src/testing/dsl.rs
- crates/aranya-runtime/src/testing/testdata/large_sync.test
- crates/aranya-runtime/src/testing/testdata/skip_list.test
- crates/aranya-runtime/src/testing/testdata/three_client_compare_graphs.test
Note from @elagergren-spideroak: We chose 512 bit IDs long before NIST’s PQ guidance (flow2, perhaps even flow1). 512 bit IDs don’t provide a meaningful improvement in collision resistance over 256 bit IDs, but they do have a negative performance impact. So, make the switch before MVP.
> Switch to 32 byte IDs

- Cargo.lock
- crates/aranya-capi-codegen-test/src/generated.rs
- crates/aranya-capi-codegen/src/ast/expand.rs
- crates/aranya-capi-codegen/src/syntax/attrs.rs
- crates/aranya-capi-codegen/src/syntax/node.rs
- crates/aranya-capi-codegen/src/syntax/opaque.rs
- crates/aranya-capi-core/Cargo.toml
- crates/aranya-capi-core/src/lib.rs
- crates/aranya-capi-core/src/opaque.rs
- crates/aranya-capi-core/src/safe.rs
- crates/aranya-capi-macro/src/opaque.rs
- supply-chain/audits.toml
The opaque macro now serves two functions. It first wraps the original type in the `Opaque` wrapper. Then it applies the `[u8; SIZE]` representation to the generated renamed type that cbindgen sees.
Closes #227.
> capi: make opaque types an exact size and alignment

- crates/aranya-capi-core/src/opaque.rs
> capi-core: fix `Opaque` use-after-free

- Cargo.lock
- Cargo.toml
- crates/aranya-crypto/Cargo.toml
- crates/aranya-crypto/src/afc/bidi.rs
- crates/aranya-crypto/src/afc/shared.rs
- crates/aranya-crypto/src/afc/uni.rs
- crates/aranya-crypto/src/aqc/bidi.rs
- crates/aranya-crypto/src/aqc/shared.rs
- crates/aranya-crypto/src/aqc/uni.rs
- crates/aranya-crypto/src/aranya.rs
- crates/aranya-crypto/src/ciphersuite/ext.rs
- crates/aranya-crypto/src/default.rs
- crates/aranya-crypto/src/groupkey.rs
- crates/aranya-crypto/src/test_util/mod.rs
- crates/aranya-crypto/src/tls/psk.rs
- crates/aranya-fast-channels/Cargo.toml
- crates/aranya-fast-channels/src/memory.rs
- crates/aranya-fast-channels/src/shm/align.rs
- crates/aranya-fast-channels/src/shm/posix.rs
- crates/aranya-fast-channels/src/shm/sdlib.rs
- crates/aranya-fast-channels/src/shm/shared.rs
- crates/aranya-fast-channels/src/state.rs
- crates/aranya-model/Cargo.toml
- crates/aranya-model/src/model.rs
- crates/aranya-model/src/tests/keygen.rs
- supply-chain/audits.toml
Removes some unneeded bounds like `where CS: Clone` which the regular derive introduces, and converts some manual impls to derives.
> all: use derive-where for better derive bounds

- crates/aranya-crypto/src/default.rs
Moves DhKemP256HkdfSha256 into a private __private module.
Fixes #293.
> crypto: hide DhKemP256HkdfSha256 in private module

- crates/aranya-policy-lang/src/bin/parser-explorer/main.rs
- crates/aranya-policy-lang/src/lang/parse.rs
- crates/aranya-policy-lang/src/lang/parse/error.rs
- crates/aranya-policy-lang/src/lang/parse/markdown.rs
- crates/aranya-policy-lang/src/lang/parse/tests.rs
Error line numbers now account for starting lines of policy chunks. E.g.
```
---
policy-version: 2
---
'''policy
let int = 0
'''
Reserved identifier: line 6 column 9: int
```
> Fix #332: Show corect line number for errors in policy chunks.

- crates/aranya-policy-ast/src/ast.rs
- crates/aranya-policy-compiler/src/compile.rs
- crates/aranya-policy-compiler/src/tests.rs
- crates/aranya-policy-lang/src/lang/parse.rs
- crates/aranya-policy-lang/src/lang/parse/policy.pest
- crates/aranya-policy-lang/src/lang/parse/tests.rs
Closes #106: Commands (and actions) now have a `persistence` field which specifies whether the command will be stored on-graph. This is specified via an optional `ephemeral` keyword, and the compiler asserts that persistent actions can only publish persistent commands, and ephemeral actions only ephemeral commands. E.g.
```
ephemeral command Foo { ... }
command Bar { ... }
ephemeral action foo() {
publish Foo { ... }
publish Bar { ... } // error: ephemeral action `foo` cannot publish persistent command `Bar`
}
```
> Add `ephemeral` keyword to actions and commands and enforce ephemeral/persistent rules at compile time.

- crates/aranya-capi-core/src/internal/error.rs
Using error! here adds a lot of chaff to the logs when using the C API, especially when using the polling-based methods like try_receive_channel (the WoudBlock response logs). This reduces the output when using levels above debug.
> logging: change error! to debug! in convert_err

- crates/aranya-policy-ast/src/ast.rs
- crates/aranya-policy-compiler/src/compile.rs
- crates/aranya-policy-compiler/src/compile/error.rs
- crates/aranya-policy-compiler/src/tests.rs
- crates/aranya-policy-lang/src/lang/parse.rs
- crates/aranya-policy-lang/src/lang/parse/policy.pest
- crates/aranya-policy-lang/test-policy.md
- crates/aranya-policy-module/src/instructions.rs
- crates/aranya-policy-vm/doc/machine-model.md
- crates/aranya-policy-vm/src/machine.rs
- crates/aranya-policy-vm/tests/vm.rs
E.g.
```
struct Foo { x int, y string }
command Bar {
fields { y string, x int }
}
action a() {
publish Foo { x: 1, y:"abc" } as Bar
}
```
> Close #193: Allow a struct to be cast to another struct with the same schema

- crates/aranya-policy-lang/src/bin/parser-explorer/main.rs
- crates/aranya-policy-lang/src/lang.rs
- crates/aranya-policy-lang/src/lang/parse.rs
- crates/aranya-policy-lang/src/lang/parse/markdown.rs
- crates/aranya-policy-lang/src/lang/parse/tests.rs
Hides `ChunkParser`, `PolicyParser`, `Rule`, `extract_policy`, `get_parser`, `parse_policy_chunk`.
Adds `parse_expression`.
> policy-lang: reduce public API

- Cargo.lock
- deny.toml
- supply-chain/audits.toml
- supply-chain/config.toml
- supply-chain/imports.lock
Closes #390.
https://rustsec.org/advisories/RUSTSEC-2025-0055
> chore: update to `tracing-subscriber@0.3.20`

- Cargo.lock
- Cargo.toml
- crates/aranya-afc-util/Cargo.toml
- crates/aranya-policy-compiler/Cargo.toml
- crates/aranya-policy-compiler/src/compile.rs
- crates/aranya-policy-compiler/src/compile/target.rs
- crates/aranya-policy-compiler/src/tests.rs
- crates/aranya-policy-ifgen-build/src/imp.rs
- crates/aranya-policy-ifgen/tests/data/tictactoe.rs
- crates/aranya-policy-module/Cargo.toml
- crates/aranya-policy-module/src/lib.rs
- crates/aranya-policy-module/src/module.rs
- crates/aranya-policy-module/src/named.rs
- crates/aranya-policy-vm/src/machine.rs
- crates/aranya-runtime/src/vm_policy.rs
Alternate approach to #360.
Since all of the maps in the module use identifier keys, I added a `NamedMap` type which is roughly `IndexSet<HashByName<T>>`.
I only added action and command defs for now since those are needed for #354 and #380.
> policy-module: add `NamedMap` and def types for action and command

- Cargo.lock
- crates/aranya-fast-channels/Cargo.toml
- crates/aranya-fast-channels/src/shm/path.rs
- supply-chain/audits.toml
Adds `Path: Serialize` and `Box<Path>: Serialize + Deserialize`.
I also changed the representation to `CStr`.
> afc: add serde impls to shm path

- crates/aranya-model/src/tests/basic-policy.md
- crates/aranya-model/src/tests/ffi-policy.md
- crates/aranya-model/src/tests/mod.rs
- crates/aranya-runtime/src/client.rs
- crates/aranya-runtime/src/client/session.rs
- crates/aranya-runtime/src/client/transaction.rs
- crates/aranya-runtime/src/engine.rs
- crates/aranya-runtime/src/testing/protocol.rs
- crates/aranya-runtime/src/testing/vm.rs
- crates/aranya-runtime/src/vm_policy.rs
Ensures that persistent actions are used on-graph and ephemeral actions are used off-graph.
I changed the API to use `ActionPlacement` and `CommandPlacement` instead of `Persistence` and `OnRecall`. I think it's more clear this way to describe how the methods are being called and have the implementations determine the correct behavior from that.
> runtime: check persistence when calling actions

- Cargo.lock
- crates/aranya-capi-codegen-test/src/defs.rs
- crates/aranya-capi-codegen-test/src/generated.rs
- crates/aranya-capi-codegen-test/src/lib.rs
- crates/aranya-capi-core/Cargo.toml
- crates/aranya-capi-core/src/internal/conv/ptr.rs
- crates/aranya-capi-core/src/safe.rs
- crates/aranya-capi-core/src/types/allowed.rs
- crates/aranya-capi-core/src/utf8.rs
We can hash the `core::any::TypeId` to get our type ID.
I verified that it optimizes down to a constant. It'd be nice to have some way to validate that remains true.
This ID won't necessarily be consistent across different compiles, but that should be fine in the way we are using it.
We now have a possibility of random collisions. It's not a huge issue since we are just using this for additional safety checks. We could increase the ID size easily, although it'd increase the size of `Safe` unless we shove the flags into either the ID or the address.
This blanket impl only applies for static types. All uses are currently static. I don't think it really makes much sense to use `Safe` with non-static types. Note we can't add manual impls since they would overlap.
> capi: add blanket Typed impl
